export interface Config {
  AUTH_SECRET: string;
  SECRET_KEY: string;
  NEXT_PUBLIC_GOONG_API_KEY: string;
  NEXT_PUBLIC_GOONG_API_MAP_KEY: string;
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: string;
  NEXT_PUBLIC_CLOUDINARY_API_KEY: string;
  CLOUDINARY_API_SECRET: string;
  NEXT_PUBLIC_DICEBEAR_API: string;
}
