import type { Metadata } from "next";
import { Plus_Jakarta_Sans as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Background from "@/components/background/Background";
import AnimatedGridBackground from "@/components/background/AnimatedGridBackground";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "EventZone",
  description: "Generated by EventZone",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("", fontSans.variable)}>
        {children}
        <AnimatedGridBackground
          numSquares={30}
          maxOpacity={0.1}
          className={cn(
            "fixed inset-x-0 inset-y-[-30%] -z-10 h-[200%] skew-y-12",
          )}
        />
      </body>
    </html>
  );
}
