import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import { Plus_Jakarta_Sans as FontSans } from "next/font/google";

import "./globals.css";
import { Toaster } from "sonner";
import RefreshUser from "@/providers/RefreshUser";
import { TooltipProvider } from "@/components/ui/tooltip";
import AnimatedGradientBackground from "@/components/shared/AminatedBackground";
import "./AnimatedGradientBackground.css";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "EventZone",
  description: "Generated by EventZone",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={cn("text-container", fontSans.variable)}>
          <TooltipProvider>
            <RefreshUser>{children}</RefreshUser>
          </TooltipProvider>
          <Toaster richColors position="top-center" />
          <AnimatedGradientBackground />
        </body>
      </html>
    </ViewTransitions>
  );
}
