import AnimatedGridBackground from "@/components/background/AnimatedGridBackground";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import { Plus_Jakarta_Sans as FontSans } from "next/font/google";
import "./globals.css";
import GlassProvider from "glass-js";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "EventZone",
  description: "Generated by EventZone",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={cn("", fontSans.variable)}>
          <GlassProvider>
            {children}
            <AnimatedGridBackground
              numSquares={30}
              maxOpacity={0.1}
              className={cn(
                "fixed inset-x-0 inset-y-[-30%] -z-10 h-[200%] skew-y-12",
              )}
            />
          </GlassProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
